// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Container': string;
  'Form': string;
  'InputBox': string;
}
export const cssExports: CssExports;
export default cssExports;
