// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'MessageItem__Avatar': string;
  'MessageItem__Container': string;
  'MessageItem__Content': string;
  'MessageItem__Left': string;
  'MessageItem__Right': string;
}
export const cssExports: CssExports;
export default cssExports;
