// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Bottom': string;
  'Container': string;
  'Top': string;
}
export const cssExports: CssExports;
export default cssExports;
